server:
  service:
    type: LoadBalancer

configs:
  params:
    server.insecure: true

controller:
  enableStatefulSet: true

additionalApplications:
  - name: root-app
    namespace: argocd
    project: default

    source:
      repoURL: https://github.com/hgiang25/k8s-gitops.git
      targetRevision: main
      path: clusters

    destination:
      server: https://kubernetes.default.svc
      namespace: argocd

    syncPolicy:
      automated:
        prune: true
        selfHeal: true

      syncOptions:
        - CreateNamespace=true
